Remove-Item –path ./client –recurse

Invoke-WebRequest -Uri 'https://api.cloudmersive.com/cdr/docs/v1/swagger' -OutFile '.\cdr-api-swagger.json'
(Get-Content .\cdr-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\cdr-api-swagger.json
(Get-Content .\cdr-api-swagger.json -Raw) -replace '"http"','"https"' | Set-Content .\cdr-api-swagger.json -Encoding UTF8

& java -jar swagger-codegen-cli-2.4.46.jar generate -i .\cdr-api-swagger.json -l javascript -o client -c packageconfig.json
(Get-Content ./client/package.json).replace('"superagent": "3.7.0"', '"superagent": "10.2.3"') | Set-Content ./client/package.json
(Get-Content ./client/README.md).replace('This SDK is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:', '[Cloudmersive CDR API](https://www.cloudmersive.com/cdr-api) provides advanced document sanitization capabilities.') | Set-Content ./client/README.md
(Get-Content ./client/README.md).replace('- Build package: io.swagger.codegen.languages.JavascriptClientCodegen', '') | Set-Content ./client/README.md
#& npm build ./client
& npm i ./client

Copy-Item ./client/README.md ./README.md