/*
 * CDR API
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveCdrApiClient);
  }
}(this, function(expect, CloudmersiveCdrApiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProblemDetails', function() {
      beforeEach(function() {
        instance = new CloudmersiveCdrApiClient.ProblemDetails();
      });

      it('should create an instance of ProblemDetails', function() {
        // TODO: update the code to test ProblemDetails
        expect(instance).to.be.a(CloudmersiveCdrApiClient.ProblemDetails);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property detail (base name: "detail")', function() {
        // TODO: update the code to test the property detail
        expect(instance).to.have.property('detail');
        // expect(instance.detail).to.be(expectedValueLiteral);
      });

      it('should have the property instance (base name: "instance")', function() {
        // TODO: update the code to test the property instance
        expect(instance).to.have.property('instance');
        // expect(instance.instance).to.be(expectedValueLiteral);
      });

    });
  });

}));
