/*
 * CDR API
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveCdrApiClient);
  }
}(this, function(expect, CloudmersiveCdrApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveCdrApiClient.FileSanitizationApi();
  });

  describe('(package)', function() {
    describe('FileSanitizationApi', function() {
      describe('file', function() {
        it('should call file successfully', function(done) {
          // TODO: uncomment, update parameter values for file call
          /*
          var opts = {};
          opts.inputFile = "/path/to/file.txt";

          instance.file(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('fileToPdf', function() {
        it('should call fileToPdf successfully', function(done) {
          // TODO: uncomment, update parameter values for fileToPdf call
          /*
          var opts = {};
          opts.inputFile = "/path/to/file.txt";

          instance.fileToPdf(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
