/*
 * CDR API
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveCdrApiClient) {
      root.CloudmersiveCdrApiClient = {};
    }
    root.CloudmersiveCdrApiClient.FileSanitizationApi = factory(root.CloudmersiveCdrApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * FileSanitization service.
   * @module api/FileSanitizationApi
   * @version 1.0.0
   */

  /**
   * Constructs a new FileSanitizationApi. 
   * @alias module:api/FileSanitizationApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the file operation.
     * @callback module:api/FileSanitizationApi~fileCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Complete Content Disarm and Reconstruction on an Input File, and output in same file format
     * Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
     * @param {Object} opts Optional parameters
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/FileSanitizationApi~fileCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.file = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/cdr/sanitization/file', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the fileToPdf operation.
     * @callback module:api/FileSanitizationApi~fileToPdfCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Complete Content Disarm and Reconstruction on an Input File with PDF/A Output
     * Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
     * @param {Object} opts Optional parameters
     * @param {File} opts.inputFile Input document, or photos of a document, to extract data from
     * @param {module:api/FileSanitizationApi~fileToPdfCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.fileToPdf = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'InputFile': opts['inputFile']
      };

      var authNames = ['Apikey'];
      var contentTypes = ['multipart/form-data'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/cdr/sanitization/file/to/pdf', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
